# Generated by Django 5.2.3 on 2025-11-10 14:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttribuutMappingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, unique=True)),
                ('medewerker_koppel_attribuut', models.CharField(choices=[('employee_number', 'Employee Number (Entra)'), ('email', 'E-mailadres'), ('username', 'User principal name (UPN)')], default='employee_number', help_text='Bepaalt op welk attribuut de koppeling tussen User en Medewerker plaatsvindt.', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FunctieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor dit functietype.', unique=True)),
                ('naam', models.CharField(help_text='De naam van het functietype (bijv. Manager, Medewerker).', max_length=50)),
                ('slug', models.SlugField(help_text='Unieke, URL-vriendelijke identificatie voor dit functietype.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Functietype',
                'verbose_name_plural': 'Functietypes',
            },
        ),
        migrations.CreateModel(
            name='Vestiging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True)),
                ('vestigingsnummer', models.CharField(help_text='Unieke identificatiecode of nummer van de vestiging.', max_length=50, unique=True)),
                ('naam', models.CharField(help_text='Volledige naam van de vestiging.', max_length=100, unique=True)),
                ('verkorte_naam', models.CharField(blank=True, help_text='Afkorting of korte naam van de vestiging.', max_length=50)),
                ('adres', models.CharField(blank=True, help_text='Fysiek adres van de vestiging (optioneel).', max_length=255)),
                ('correspondentieadres', models.CharField(blank=True, help_text='Adres voor correspondentie (optioneel).', max_length=255)),
                ('post_adres', models.CharField(blank=True, help_text='Post adres van de vestiging (optioneel).', max_length=255)),
                ('telefoonnummer', models.CharField(blank=True, help_text='Telefoonnummer van de vestiging (optioneel).', max_length=50)),
                ('landcode', models.CharField(blank=True, help_text='ISO-landcode van de vestiging (bijv. NL, BE).', max_length=2)),
            ],
            options={
                'verbose_name': 'Vestiging',
                'verbose_name_plural': 'Vestigingen',
            },
        ),
        migrations.CreateModel(
            name='Functie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor deze functie.', unique=True)),
                ('functie_omschrijving', models.CharField(help_text='Korte omschrijving of titel van de functie.', max_length=255)),
                ('begin_datum', models.DateField(help_text='De datum waarop de functie ingaat.')),
                ('eind_datum', models.DateField(blank=True, help_text='De datum waarop de functie eindigt.', null=True)),
                ('functie_type', models.ForeignKey(help_text='Het type functie dat hieraan gekoppeld is.', on_delete=django.db.models.deletion.CASCADE, related_name='functies', to='organisatie.functietype')),
            ],
            options={
                'verbose_name': 'Functie',
                'verbose_name_plural': 'Functies',
            },
        ),
        migrations.CreateModel(
            name='Medewerker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True)),
                ('medewerker_id', models.CharField(help_text='ID van de medewerker.', max_length=50, unique=True)),
                ('voornaam', models.CharField(help_text='Voornaam van de medewerker.', max_length=100)),
                ('achternaam', models.CharField(help_text='Achternaam van de medewerker.', max_length=100)),
                ('emailadres', models.EmailField(help_text='E-mailadres van de medewerker.', max_length=254, unique=True)),
                ('telefoonnummer', models.CharField(blank=True, help_text='Telefoonnummer van de medewerker (optioneel).', max_length=30)),
                ('geslachtsaanduiding', models.CharField(blank=True, choices=[('M', 'Man'), ('V', 'Vrouw'), ('X', 'Anders')], help_text='Geslachtsaanduiding (optioneel).', max_length=10)),
                ('datum_uit_dienst', models.DateField(blank=True, help_text='Datum waarop de medewerker uit dienst is gegaan (indien van toepassing).', null=True)),
                ('datum_toegevoegd', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Datum waarop de medewerker is toegevoegd.')),
                ('datum_aangepast', models.DateTimeField(auto_now=True, help_text='Datum waarop de medewerker voor het laatst is gewijzigd.')),
                ('functies', models.ManyToManyField(blank=True, help_text='Functies van de medewerker.', related_name='medewerkers', to='organisatie.functie')),
            ],
            options={
                'verbose_name': 'Medewerker',
                'verbose_name_plural': 'Medewerkers',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True)),
                ('naam', models.CharField(help_text='Naam van het team.', max_length=100, unique=True)),
                ('omschrijving', models.TextField(blank=True, help_text='Optionele omschrijving van het team.')),
                ('contactpersoon', models.ForeignKey(blank=True, help_text='De medewerker die contactpersoon is voor dit team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_als_contactpersoon', to='organisatie.medewerker')),
                ('functies', models.ManyToManyField(blank=True, help_text='Functies die binnen dit team actief zijn.', related_name='teams', to='organisatie.functie', verbose_name='Functies')),
                ('vestigingen', models.ManyToManyField(blank=True, help_text='Vestigingen waaraan de medewerker gekoppeld is.', related_name='teams', to='organisatie.vestiging')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.AddField(
            model_name='medewerker',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='Teams van de medewerker.', related_name='medewerkers', to='organisatie.team'),
        ),
        migrations.CreateModel(
            name='OrganisatorischeEenheid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True)),
                ('identificatie', models.CharField(help_text='Unieke interne identificatie van de organisatorische eenheid.', max_length=50, unique=True)),
                ('naam', models.CharField(help_text='Volledige naam van de organisatorische eenheid.', max_length=100, unique=True)),
                ('soort_organisatie', models.CharField(help_text='Soort organisatorische eenheid.', max_length=50)),
                ('verkorte_naam', models.CharField(blank=True, help_text='Afkorting of verkorte naam van de organisatorische eenheid.', max_length=50)),
                ('omschrijving', models.TextField(blank=True, help_text='Optionele omschrijving van de organisatorische eenheid.')),
                ('emailadres', models.EmailField(blank=True, help_text='E-mailadres van de organisatorische eenheid.', max_length=254)),
                ('telefoonnummer', models.CharField(blank=True, help_text='Telefoonnummer van de organisatorische eenheid.', max_length=50)),
                ('datum_opheffing', models.DateField(blank=True, help_text='Optionele datum waarop de organisatorische eenheid wordt opgeheven.', null=True)),
                ('contactpersoon', models.ForeignKey(blank=True, help_text='De medewerker die contactpersoon is voor deze organisatorische eenheid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisatorische_eenheden_als_contactpersoon', to='organisatie.medewerker')),
                ('functies', models.ManyToManyField(blank=True, help_text='Functies binnen deze organisatorische eenheid.', related_name='organisatorische_eenheden', to='organisatie.functie', verbose_name='Functies')),
                ('hoofd_organisatorische_eenheid', models.ForeignKey(blank=True, help_text='Optionele bovenliggende organisatorische eenheid.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_organisatorische_eenheden', to='organisatie.organisatorischeeenheid')),
                ('vestigingen', models.ManyToManyField(blank=True, help_text='Vestigingen waaraan de medewerker gekoppeld is.', related_name='organisatorische_eenheden', to='organisatie.vestiging')),
            ],
            options={
                'verbose_name': 'Organisatorische Eenheid',
                'verbose_name_plural': 'Organisatorische Eenheden',
            },
        ),
    ]
