# Generated by Django 5.2.9 on 2026-03-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisatie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functie',
            old_name='eind_datum',
            new_name='einddatum',
        ),
        migrations.RemoveField(
            model_name='functie',
            name='begin_datum',
        ),
        migrations.RemoveField(
            model_name='medewerker',
            name='datum_aangepast',
        ),
        migrations.RemoveField(
            model_name='medewerker',
            name='datum_toegevoegd',
        ),
        migrations.RemoveField(
            model_name='medewerker',
            name='datum_uit_dienst',
        ),
        migrations.RemoveField(
            model_name='organisatorischeeenheid',
            name='datum_opheffing',
        ),
        migrations.RemoveField(
            model_name='vestiging',
            name='landcode',
        ),
        migrations.RemoveField(
            model_name='vestiging',
            name='verkorte_naam',
        ),
        migrations.AddField(
            model_name='functie',
            name='startdatum',
            field=models.DateField(blank=True, help_text='De datum waarop de functie ingaat.', null=True),
        ),
        migrations.AddField(
            model_name='functie',
            name='wijzigingsdatum',
            field=models.DateTimeField(blank=True, help_text='De datum waarop de functie gewijzigd is.', null=True),
        ),
        migrations.AddField(
            model_name='medewerker',
            name='einddatum',
            field=models.DateField(blank=True, help_text='De datum waarop de medewerker uit dienst gaat.', null=True),
        ),
        migrations.AddField(
            model_name='medewerker',
            name='startdatum',
            field=models.DateField(blank=True, help_text='De datum waarop de medewerker in dienst gaat.', null=True),
        ),
        migrations.AddField(
            model_name='medewerker',
            name='wijzigingsdatum',
            field=models.DateTimeField(blank=True, help_text='De datum waarop de medewerker gewijzigd is.', null=True),
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='einddatum',
            field=models.DateField(blank=True, help_text='De datum waarop de organisatorische eenheid eindigt.', null=True),
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='startdatum',
            field=models.DateField(blank=True, help_text='De datum waarop de organisatorische eenheid start.', null=True),
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='wijzigingsdatum',
            field=models.DateTimeField(blank=True, help_text='De datum waarop de organisatorische eenheid gewijzigd is.', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='einddatum',
            field=models.DateField(blank=True, help_text='De datum waarop het team eindigt.', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='emailadres',
            field=models.EmailField(blank=True, help_text='E-mailadres van het team.', max_length=254),
        ),
        migrations.AddField(
            model_name='team',
            name='soort_team',
            field=models.CharField(blank=True, help_text='Soort team.', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='startdatum',
            field=models.DateField(blank=True, help_text='De datum waarop het team ingaat.', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='telefoonnummer',
            field=models.CharField(blank=True, help_text='Telefoonnummer van het team.', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='wijzigingsdatum',
            field=models.DateTimeField(blank=True, help_text='De datum waarop het team gewijzigd is.', null=True),
        ),
        migrations.AddField(
            model_name='vestiging',
            name='kvk_nummer',
            field=models.CharField(blank=True, help_text='KVK nummer van de vestiging.', max_length=50),
        ),
        migrations.AlterField(
            model_name='vestiging',
            name='vestigingsnummer',
            field=models.CharField(blank=True, help_text='Unieke identificatiecode of nummer van de vestiging.', max_length=50, unique=True),
        ),
    ]
