# Generated by Django 5.2.13 on 2026-04-29 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisatie', '0002_rename_eind_datum_functie_einddatum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medewerker',
            name='functies',
        ),
        migrations.RemoveField(
            model_name='medewerker',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='organisatorischeeenheid',
            name='functies',
        ),
        migrations.RemoveField(
            model_name='team',
            name='functies',
        ),
        migrations.AddField(
            model_name='functie',
            name='medewerker',
            field=models.ForeignKey(blank=True, help_text='De medewerker die aan deze functie gekoppeld is.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functies', to='organisatie.medewerker'),
        ),
        migrations.CreateModel(
            name='FunctieTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdatum', models.DateField(help_text='De datum waarop de functie begint.')),
                ('einddatum', models.DateField(blank=True, help_text='De datum waarop de functie eindigd.', null=True)),
                ('wijzigingsdatum', models.DateTimeField(auto_now=True)),
                ('functie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisatie.functie')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisatie.team')),
            ],
            options={
                'verbose_name': 'Functie Team',
                'verbose_name_plural': 'Functie teams',
            },
        ),
        migrations.AddField(
            model_name='functie',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='Teams van de functie.', related_name='functies', through='organisatie.FunctieTeam', to='organisatie.team'),
        ),
        migrations.CreateModel(
            name='OrganisatorischeEenheidFunctie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdatum', models.DateField()),
                ('einddatum', models.DateField(blank=True, null=True)),
                ('wijzigingsdatum', models.DateTimeField(auto_now=True)),
                ('functie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisatie.functie')),
                ('organisatorische_eenheid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisatie.organisatorischeeenheid')),
            ],
            options={
                'verbose_name': 'Functie organisatorische eenheden',
                'verbose_name_plural': 'Functie organisatorische eenheden',
            },
        ),
        migrations.AddField(
            model_name='functie',
            name='organisatorische_eenheid',
            field=models.ManyToManyField(blank=True, help_text='Organisatorische eenheden van de functie.', related_name='functies', through='organisatie.OrganisatorischeEenheidFunctie', to='organisatie.organisatorischeeenheid'),
        ),
    ]
