# Generated by Django 5.2.9 on 2026-04-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisatie', '0002_rename_eind_datum_functie_einddatum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='functie',
            name='external_id',
            field=models.CharField(blank=True, help_text='Externe identifier voor deze functie.', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='functietype',
            name='external_id',
            field=models.CharField(blank=True, help_text='Externe identifier voor deze functietype.', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='medewerker',
            name='external_id',
            field=models.CharField(blank=True, help_text='Externe identifier voor deze medewerker.', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='external_id',
            field=models.CharField(blank=True, help_text='Externe identifier voor deze organisatorische eenheid.', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='external_id',
            field=models.CharField(blank=True, help_text='Externe identifier voor dit team.', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='vestiging',
            name='external_id',
            field=models.CharField(blank=True, help_text='Externe identifier voor deze vestiging.', max_length=255, unique=True),
        ),
    ]
