# Generated by Django 5.2.13 on 2026-06-11 14:23

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGistExtension

class Migration(migrations.Migration):

    dependencies = [
        ('organisatie', '0003_functie_external_id_functietype_external_id_and_more'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.RemoveField(
            model_name='medewerker',
            name='functies',
        ),
        migrations.RemoveField(
            model_name='medewerker',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='organisatorischeeenheid',
            name='functies',
        ),
        migrations.RemoveField(
            model_name='team',
            name='functies',
        ),
        migrations.AddField(
            model_name='functie',
            name='medewerker',
            field=models.ForeignKey(blank=True, help_text='De medewerker die aan deze functie gekoppeld is.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functies', to='organisatie.medewerker'),
        ),
        migrations.CreateModel(
            name='FunctieTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wijzigingsdatum', models.DateTimeField(auto_now=True)),
                ('geldigheid', django.contrib.postgres.fields.ranges.DateRangeField(help_text='Geldigheidsperiode van deze relatie.')),
                ('functie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisatie.functie')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisatie.team')),
            ],
            options={
                'verbose_name': 'Functie Team',
                'verbose_name_plural': 'Functie teams',
            },
        ),
        migrations.AddField(
            model_name='functie',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='Teams van de functie.', related_name='functies', through='organisatie.FunctieTeam', to='organisatie.team'),
        ),
        migrations.CreateModel(
            name='OrganisatorischeEenheidFunctie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wijzigingsdatum', models.DateTimeField(auto_now=True)),
                ('geldigheid', django.contrib.postgres.fields.ranges.DateRangeField(help_text='Geldigheidsperiode van deze relatie.')),
                ('functie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisatie.functie')),
                ('organisatorische_eenheid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisatie.organisatorischeeenheid')),
            ],
            options={
                'verbose_name': 'Functie organisatorische eenheden',
                'verbose_name_plural': 'Functie organisatorische eenheden',
            },
        ),
        migrations.AddField(
            model_name='functie',
            name='organisatorische_eenheid',
            field=models.ManyToManyField(blank=True, help_text='Organisatorische eenheden van de functie.', related_name='functies', through='organisatie.OrganisatorischeEenheidFunctie', to='organisatie.organisatorischeeenheid'),
        ),
        migrations.AddConstraint(
            model_name='functieteam',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('functie', '='), ('team', '='), ('geldigheid', '&&')], name='no_overlapping_functie_team_geldigheid'),
        ),
        migrations.AddConstraint(
            model_name='organisatorischeeenheidfunctie',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('functie', '='), ('organisatorische_eenheid', '='), ('geldigheid', '&&')], name='no_overlapping_organisatie_functie_geldigheid'),
        ),
    ]
