# Generated by Django 5.2.15 on 2026-06-26 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisatie', '0004_remove_medewerker_functies_remove_medewerker_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='functie',
            name='vervanger',
            field=models.ForeignKey(blank=True, help_text='Verwijzing naar de functie die deze functie vervangt bij afwezigheid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vervangen_functies', to='organisatie.functie'),
        ),
    ]
