[tool.pyright]
pythonVersion = "3.12"
pythonPlatform = "Linux"
reportUnnecessaryTypeIgnoreComment = "error"
include = ["src"]
exclude = [
    "src/openorganisatie/conf", 
    "src/openorganisatie/accounts",  # inherited from default-project  
    "src/openorganisatie/organisatie/api/tests",
    "src/openorganisatie/utils",
    "src/openorganisatie/celery.py",
    "src/openorganisatie/setup.py",
    "src/openorganisatie/urls.py",
]