# Generated by Django 5.2.3 on 2025-06-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medewerker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medewerker_id', models.CharField(max_length=255, unique=True)),
                ('voornaam', models.CharField(max_length=100)),
                ('achternaam', models.CharField(max_length=100)),
                ('emailadres', models.EmailField(max_length=254, unique=True)),
                ('functie', models.CharField(blank=True, max_length=100)),
                ('telefoonnummer', models.CharField(blank=True, max_length=30)),
                ('geslachtsaanduiding', models.BooleanField(default=True)),
                ('datum_uit_dienst', models.DateField(blank=True, null=True)),
                ('actief', models.BooleanField(default=True)),
            ],
        ),
    ]
