# Generated by Django 5.2.3 on 2025-10-03 14:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor dit functietype.', unique=True)),
                ('naam', models.CharField(help_text='De naam van het functietype (bijv. Manager, Medewerker).', max_length=50, verbose_name='Naam')),
                ('slug', models.SlugField(help_text='Unieke, URL-vriendelijke identificatie voor dit functietype.', max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Functietype',
                'verbose_name_plural': 'Functietypes',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scim_id', models.CharField(blank=True, default=None, help_text='A unique identifier for a SCIM resource as defined by the service provider.', max_length=254, null=True, unique=True, verbose_name='SCIM ID')),
                ('scim_external_id', models.CharField(blank=True, db_index=True, default=None, help_text='A string that is an identifier for the resource as defined by the provisioning client.', max_length=254, null=True, verbose_name='SCIM External ID')),
                ('scim_display_name', models.CharField(blank=True, db_index=True, default=None, help_text='A human-readable name for the Group.', max_length=254, null=True, verbose_name='SCIM Display Name')),
                ('name', models.CharField(help_text='Naam van het team.', max_length=100, unique=True, verbose_name='Naam')),
                ('description', models.TextField(blank=True, help_text='Optionele beschrijving van het team.', verbose_name='Beschrijving')),
                ('active', models.BooleanField(default=True, help_text='Geeft aan of het team momenteel actief is.', verbose_name='Actief')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Vestiging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True)),
                ('branchnumber', models.CharField(help_text='Unieke identificatiecode of nummer van de vestiging.', max_length=50, unique=True, verbose_name='Vestigingsnummer')),
                ('branchname', models.CharField(help_text='Volledige naam van de vestiging.', max_length=100, unique=True, verbose_name='Naam')),
                ('short_name', models.CharField(blank=True, help_text='Afkorting of korte naam van de vestiging.', max_length=50, verbose_name='Korte naam')),
                ('address', models.CharField(blank=True, help_text='Fysiek adres van de vestiging (optioneel).', max_length=255, verbose_name='Adres')),
                ('correspondence_address', models.CharField(blank=True, help_text='Adres voor correspondentie (optioneel).', max_length=255, verbose_name='Correspondentieadres')),
                ('postal_address', models.CharField(blank=True, help_text='Post adres van de vestiging (optioneel).', max_length=255, verbose_name='Post adres')),
                ('phone_number', models.CharField(blank=True, help_text='Telefoonnummer van de vestiging (optioneel).', max_length=50, verbose_name='Telefoonnummer')),
                ('country_code', models.CharField(blank=True, help_text='ISO-landcode van de vestiging (bijv. NL, BE).', max_length=2, verbose_name='Landcode')),
            ],
            options={
                'verbose_name': 'Vestiging',
                'verbose_name_plural': 'Vestigingen',
            },
        ),
        migrations.CreateModel(
            name='Functie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4) voor deze functie.', unique=True)),
                ('functie_omschrijving', models.CharField(help_text='Korte omschrijving of titel van de functie.', max_length=255, verbose_name='Functie omschrijving')),
                ('begin_datum', models.DateField(help_text='De datum waarop de functie ingaat.', verbose_name='Begindatum')),
                ('eind_datum', models.DateField(blank=True, help_text='De datum waarop de functie eindigt.', null=True, verbose_name='Einddatum')),
                ('functie_type', models.ForeignKey(help_text='Het type functie dat hieraan gekoppeld is.', on_delete=django.db.models.deletion.CASCADE, related_name='functies', to='scim.functietype', verbose_name='Functietype')),
            ],
            options={
                'verbose_name': 'Functie',
                'verbose_name_plural': 'Functies',
            },
        ),
        migrations.CreateModel(
            name='OrganisatorischeEenheid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True)),
                ('identifier', models.CharField(help_text='Unieke interne identificatie van de organisatorische eenheid.', max_length=50, unique=True, verbose_name='Identificatie')),
                ('name', models.CharField(help_text='Volledige naam van de organisatorische eenheid.', max_length=100, unique=True, verbose_name='Naam')),
                ('organization_type', models.CharField(help_text='Type organisatie.', max_length=50, verbose_name='Type organisatie')),
                ('short_name', models.CharField(blank=True, help_text='Afkorting of verkorte naam van de organisatorische eenheid.', max_length=50, verbose_name='Verkorte naam')),
                ('description', models.TextField(blank=True, help_text='Optionele beschrijving van de organisatorische eenheid.', verbose_name='Beschrijving')),
                ('email_address', models.EmailField(blank=True, help_text='E-mailadres van de organisatorische eenheid.', max_length=254, verbose_name='E-mailadres')),
                ('phone_number', models.CharField(blank=True, help_text='Telefoonnummer van de organisatorische eenheid.', max_length=50, verbose_name='Telefoonnummer')),
                ('end_date', models.DateField(blank=True, help_text='Optionele einddatum waarop de organisatorische eenheid wordt opgeheven of stopt te bestaan.', null=True, verbose_name='Einddatum')),
                ('functies', models.ManyToManyField(blank=True, help_text='Functies binnen deze organisatorische eenheid.', related_name='organisatorische_eenheden', to='scim.functie', verbose_name='Functies')),
                ('parent_organisation', models.ForeignKey(blank=True, help_text='Optionele bovenliggende organisatorische eenheid.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_organisatorische_eenheden', to='scim.organisatorischeeenheid', verbose_name='Bovenliggende eenheid')),
                ('branches', models.ManyToManyField(blank=True, help_text='Vestigingen waaraan de medewerker gekoppeld is.', related_name='organisatorische_eenheden', to='scim.vestiging', verbose_name='Vestigingen')),
            ],
            options={
                'verbose_name': 'Organisatorische Eenheid',
                'verbose_name_plural': 'Organisatorische Eenheden',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scim_id', models.CharField(blank=True, default=None, help_text='A unique identifier for a SCIM resource as defined by the service provider.', max_length=254, null=True, unique=True, verbose_name='SCIM ID')),
                ('scim_external_id', models.CharField(blank=True, db_index=True, default=None, help_text='A string that is an identifier for the resource as defined by the provisioning client.', max_length=254, null=True, verbose_name='SCIM External ID')),
                ('scim_display_name', models.CharField(blank=True, db_index=True, default=None, help_text='A human-readable name for the Group.', max_length=254, null=True, verbose_name='SCIM Display Name')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True)),
                ('name', models.CharField(help_text='Naam van het team.', max_length=100, unique=True, verbose_name='Naam')),
                ('description', models.TextField(blank=True, help_text='Optionele beschrijving van het team.', verbose_name='Beschrijving')),
                ('functies', models.ManyToManyField(blank=True, help_text='Functies die binnen dit team actief zijn.', related_name='teams', to='scim.functie', verbose_name='Functies')),
                ('branches', models.ManyToManyField(blank=True, help_text='Vestigingen waaraan de medewerker gekoppeld is.', related_name='teams', to='scim.vestiging', verbose_name='Vestigingen')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Medewerker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True)),
                ('medewerker_id', models.CharField(help_text='ID van de medewerker.', max_length=50, unique=True, verbose_name='Medewerker ID')),
                ('first_name', models.CharField(help_text='Voornaam van de medewerker.', max_length=100, verbose_name='Voornaam')),
                ('last_name', models.CharField(help_text='Achternaam van de medewerker.', max_length=100, verbose_name='Achternaam')),
                ('email', models.EmailField(help_text='E-mailadres van de medewerker.', max_length=254, unique=True, verbose_name='E-mailadres')),
                ('phone_number', models.CharField(blank=True, help_text='Telefoonnummer van de medewerker (optioneel).', max_length=30, verbose_name='Telefoonnummer')),
                ('gender_indicator', models.CharField(blank=True, choices=[('M', 'Man'), ('V', 'Vrouw'), ('X', 'Anders')], help_text='Geslachtsaanduiding (optioneel).', max_length=10, verbose_name='Geslachtsaanduiding')),
                ('termination_date', models.DateField(blank=True, help_text='Datum waarop de medewerker uit dienst is gegaan (indien van toepassing).', null=True, verbose_name='Datum uit dienst')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Datum waarop de medewerker is toegevoegd.', verbose_name='Datum toegevoegd')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Datum waarop de medewerker voor het laatst is gewijzigd.', verbose_name='Laatst gewijzigd')),
                ('functies', models.ManyToManyField(blank=True, help_text='Functies van de medewerker.', related_name='medewerkers', to='scim.functie', verbose_name='Functies')),
                ('organisatorische_eenheden', models.ManyToManyField(blank=True, help_text='Organisatorische eenheden waartoe de medewerker behoort.', related_name='medewerkers', to='scim.organisatorischeeenheid', verbose_name='Organisatorische Eenheden')),
                ('teams', models.ManyToManyField(blank=True, help_text='Teams van de medewerker.', related_name='medewerkers', to='scim.team', verbose_name='Teams')),
            ],
            options={
                'verbose_name': 'Medewerker',
                'verbose_name_plural': 'Medewerkers',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scim_id', models.CharField(blank=True, default=None, help_text='A unique identifier for a SCIM resource as defined by the service provider.', max_length=254, null=True, unique=True, verbose_name='SCIM ID')),
                ('scim_external_id', models.CharField(blank=True, db_index=True, default=None, help_text='A string that is an identifier for the resource as defined by the provisioning client.', max_length=254, null=True, verbose_name='SCIM External ID')),
                ('scim_username', models.CharField(blank=True, db_index=True, default=None, help_text="A service provider's unique identifier for the user", max_length=254, null=True, verbose_name='SCIM Username')),
                ('username', models.CharField(editable=False, help_text='User principal name van de medewerker.', max_length=100, verbose_name='User principal name')),
                ('first_name', models.CharField(help_text='Voornaam van de medewerker.', max_length=100, verbose_name='Voornaam')),
                ('last_name', models.CharField(help_text='Achternaam van de medewerker.', max_length=100, verbose_name='Achternaam')),
                ('email', models.EmailField(help_text='E-mailadres van de medewerker.', max_length=254, unique=True, verbose_name='E-mailadres')),
                ('job_title', models.CharField(blank=True, help_text='Functie van de medewerker (optioneel).', max_length=100, verbose_name='Functie')),
                ('phone_number', models.CharField(blank=True, help_text='Telefoonnummer van de medewerker (optioneel).', max_length=30, verbose_name='Telefoonnummer')),
                ('is_active', models.BooleanField(default=True, help_text='Geeft aan of de medewerker momenteel actief is.', verbose_name='Actief')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Datum waarop de medewerker is toegevoegd.', verbose_name='Datum toegevoegd')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Datum waarop de medewerker voor het laatst is gewijzigd.', verbose_name='Laatst gewijzigd')),
                ('groups', models.ManyToManyField(blank=True, help_text='Groups van de user.', related_name='user_set', to='scim.group', verbose_name='Groups')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Contactpersoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True)),
                ('medewerker', models.ForeignKey(help_text='De medewerker die aan deze rol gekoppeld is.', on_delete=django.db.models.deletion.CASCADE, related_name='contactpersoon_roles', to='scim.medewerker', verbose_name='Medewerker')),
                ('organisatorische_eenheid', models.ForeignKey(blank=True, help_text='Organisatorische eenheid waaraan de medewerker gekoppeld is.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactpersonen', to='scim.organisatorischeeenheid', verbose_name='Organisatorische Eenheid')),
                ('team', models.ForeignKey(blank=True, help_text='Team waaraan de medewerker gekoppeld is.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactpersonen', to='scim.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Contactpersoon',
                'verbose_name_plural': 'Contactpersonen',
                'unique_together': {('medewerker', 'team', 'organisatorische_eenheid')},
            },
        ),
    ]
