# Generated by Django 5.2.3 on 2025-09-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medewerker',
            name='app_roles',
            field=models.JSONField(blank=True, default=list, help_text='App-rollen van de medewerker in Entra ID, opgeslagen als een lijst van dicts.', verbose_name='App-rollen'),
        ),
    ]
