# Generated by Django 5.2.3 on 2025-07-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medewerker',
            name='geslachtsaanduiding',
            field=models.BooleanField(default=True, help_text='Geslachtsaanduiding: waar of niet waar.???(staat zo in datamodel)'),
        ),
    ]
