# Generated by Django 5.2.3 on 2025-07-21 08:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisatorischeEenheid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Naam van de organisatorische eenheid.', max_length=100, unique=True, verbose_name='Naam')),
                ('description', models.TextField(blank=True, help_text='Optionele beschrijving van de organisatorische eenheid.', verbose_name='Beschrijving')),
                ('active', models.BooleanField(default=True, help_text='Geeft aan of de organisatorische eenheid actief is.', verbose_name='Actief')),
            ],
            options={
                'verbose_name': 'Organisatorische Eenheid',
                'verbose_name_plural': 'Organisatorische Eenheden',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scim_id', models.CharField(blank=True, default=None, help_text='A unique identifier for a SCIM resource as defined by the service provider.', max_length=254, null=True, unique=True, verbose_name='SCIM ID')),
                ('scim_external_id', models.CharField(blank=True, db_index=True, default=None, help_text='A string that is an identifier for the resource as defined by the provisioning client.', max_length=254, null=True, verbose_name='SCIM External ID')),
                ('scim_display_name', models.CharField(blank=True, db_index=True, default=None, help_text='A human-readable name for the Group.', max_length=254, null=True, verbose_name='SCIM Display Name')),
                ('name', models.CharField(help_text='Naam van het team.', max_length=100, unique=True, verbose_name='Naam')),
                ('description', models.TextField(blank=True, help_text='Optionele beschrijving van het team.', verbose_name='Beschrijving')),
                ('active', models.BooleanField(default=True, help_text='Geeft aan of het team momenteel actief is.', verbose_name='Actief')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.AlterModelOptions(
            name='medewerker',
            options={'verbose_name': 'Medewerker', 'verbose_name_plural': 'Medewerkers'},
        ),
        migrations.AddField(
            model_name='medewerker',
            name='scim_groups',
            field=models.ManyToManyField(blank=True, help_text='Teams van de medewerker.', related_name='user_set', to='scim.team', verbose_name='Teams'),
        ),
        migrations.CreateModel(
            name='Vestiging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Naam van de vestiging.', max_length=100, unique=True, verbose_name='Naam')),
                ('address', models.CharField(blank=True, help_text='Adres van de vestiging (optioneel).', max_length=255, verbose_name='Adres')),
                ('active', models.BooleanField(default=True, help_text='Geeft aan of de vestiging momenteel actief is.', verbose_name='Actief')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Datum waarop de vestiging is toegevoegd.', verbose_name='Datum toegevoegd')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Datum waarop de vestiging voor het laatst is gewijzigd.', verbose_name='Laatst gewijzigd')),
                ('employees', models.ManyToManyField(blank=True, help_text='Medewerkers die aan deze vestiging gekoppeld zijn.', related_name='vestigingen', to='scim.medewerker', verbose_name='Medewerkers')),
                ('organisational_unit', models.ForeignKey(help_text='De organisatorische eenheid waartoe deze vestiging behoort.', on_delete=django.db.models.deletion.CASCADE, related_name='vestigingen', to='scim.organisatorischeeenheid', verbose_name='Organisatorische eenheid')),
            ],
            options={
                'verbose_name': 'Vestiging',
                'verbose_name_plural': 'Vestigingen',
            },
        ),
    ]
