# Generated by Django 5.2.3 on 2025-07-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisatorischeEenheid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(help_text='Naam van de organisatorische eenheid.', max_length=100, unique=True)),
                ('beschrijving', models.TextField(blank=True, help_text='Optionele beschrijving van de organisatorische eenheid.')),
                ('actief', models.BooleanField(default=True, help_text='Geeft aan of de organisatorische eenheid actief is.')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(help_text='Naam van het team.', max_length=100, unique=True)),
                ('beschrijving', models.TextField(blank=True, help_text='Optionele beschrijving van het team.')),
                ('actief', models.BooleanField(default=True, help_text='Geeft aan of het team momenteel actief is.')),
                ('leden', models.ManyToManyField(blank=True, help_text='Medewerkers die lid zijn van dit team.', related_name='teams', to='scim.medewerker')),
            ],
        ),
        migrations.CreateModel(
            name='Vestiging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(help_text='Naam van de vestiging.', max_length=100, unique=True)),
                ('adres', models.CharField(blank=True, help_text='Adres van de vestiging (optioneel).', max_length=255)),
                ('actief', models.BooleanField(default=True, help_text='Geeft aan of de vestiging momenteel actief is.')),
                ('medewerkers', models.ManyToManyField(blank=True, help_text='Medewerkers die aan deze vestiging gekoppeld zijn.', related_name='vestigingen', to='scim.medewerker')),
                ('organisatorische_eenheid', models.ForeignKey(help_text='De organisatorische eenheid waartoe deze vestiging behoort.', on_delete=django.db.models.deletion.CASCADE, related_name='vestigingen', to='scim.organisatorischeeenheid')),
            ],
        ),
    ]
