# Generated by Django 5.2.3 on 2025-10-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactpersoon',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contactpersoon',
            name='organisatorische_eenheden',
            field=models.ManyToManyField(blank=True, help_text='Organisatorische eenheden waaraan de medewerker gekoppeld is.', related_name='contactpersonen', to='scim.organisatorischeeenheid', verbose_name='Organisatorische Eenheden'),
        ),
        migrations.AddField(
            model_name='contactpersoon',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='Teams waaraan de medewerker gekoppeld is.', related_name='contactpersonen', to='scim.team', verbose_name='Teams'),
        ),
        migrations.RemoveField(
            model_name='contactpersoon',
            name='organisatorische_eenheid',
        ),
        migrations.RemoveField(
            model_name='contactpersoon',
            name='team',
        ),
    ]
