# Generated by Django 5.2.3 on 2025-10-14 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttribuutMappingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, unique=True)),
                ('medewerker_koppel_attribuut', models.CharField(choices=[('employee_number', 'Employee Number (Entra)'), ('email', 'E-mailadres'), ('username', 'User principal name (UPN)')], default='employee_number', help_text='Bepaalt op welk attribuut de koppeling tussen User en Medewerker plaatsvindt.', max_length=50)),
                ('actief', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='employee_number',
            field=models.CharField(blank=True, help_text='Unieke employeeNumber uit Entra / SCIM.', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='medewerker',
            field=models.ForeignKey(blank=True, help_text='De gekoppelde medewerker (optioneel, wordt automatisch gekoppeld).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='scim.medewerker'),
        ),
    ]
