# Generated by Django 5.2.3 on 2025-10-10 10:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0002_alter_contactpersoon_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medewerker',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='medewerker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='medewerker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='medewerker',
            name='gender_indicator',
        ),
        migrations.RemoveField(
            model_name='medewerker',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='medewerker',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='medewerker',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='medewerker',
            name='termination_date',
        ),
        migrations.RemoveField(
            model_name='organisatorischeeenheid',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='organisatorischeeenheid',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organisatorischeeenheid',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='organisatorischeeenheid',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='organisatorischeeenheid',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='organisatorischeeenheid',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organisatorischeeenheid',
            name='organization_type',
        ),
        migrations.RemoveField(
            model_name='organisatorischeeenheid',
            name='parent_organisation',
        ),
        migrations.RemoveField(
            model_name='organisatorischeeenheid',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='organisatorischeeenheid',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='scim_display_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='scim_external_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='scim_id',
        ),
        migrations.RemoveField(
            model_name='vestiging',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vestiging',
            name='branchname',
        ),
        migrations.RemoveField(
            model_name='vestiging',
            name='branchnumber',
        ),
        migrations.RemoveField(
            model_name='vestiging',
            name='correspondence_address',
        ),
        migrations.RemoveField(
            model_name='vestiging',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='vestiging',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='vestiging',
            name='postal_address',
        ),
        migrations.RemoveField(
            model_name='vestiging',
            name='short_name',
        ),
        migrations.AddField(
            model_name='medewerker',
            name='achternaam',
            field=models.CharField(default=1, help_text='Achternaam van de medewerker.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medewerker',
            name='datum_aangepast',
            field=models.DateTimeField(auto_now=True, help_text='Datum waarop de medewerker voor het laatst is gewijzigd.'),
        ),
        migrations.AddField(
            model_name='medewerker',
            name='datum_toegevoegd',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Datum waarop de medewerker is toegevoegd.'),
        ),
        migrations.AddField(
            model_name='medewerker',
            name='datum_uit_dienst',
            field=models.DateField(blank=True, help_text='Datum waarop de medewerker uit dienst is gegaan (indien van toepassing).', null=True),
        ),
        migrations.AddField(
            model_name='medewerker',
            name='emailadres',
            field=models.EmailField(default=1, help_text='E-mailadres van de medewerker.', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medewerker',
            name='geslachtsaanduiding',
            field=models.CharField(blank=True, choices=[('M', 'Man'), ('V', 'Vrouw'), ('X', 'Anders')], help_text='Geslachtsaanduiding (optioneel).', max_length=10),
        ),
        migrations.AddField(
            model_name='medewerker',
            name='telefoonnummer',
            field=models.CharField(blank=True, help_text='Telefoonnummer van de medewerker (optioneel).', max_length=30),
        ),
        migrations.AddField(
            model_name='medewerker',
            name='voornaam',
            field=models.CharField(default=1, help_text='Voornaam van de medewerker.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='datum_opheffing',
            field=models.DateField(blank=True, help_text='Optionele datum waarop de organisatorische eenheid wordt opgeheven.', null=True),
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='emailadres',
            field=models.EmailField(blank=True, help_text='E-mailadres van de organisatorische eenheid.', max_length=254),
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='hoofd_organisatorische_eenheid',
            field=models.ForeignKey(blank=True, help_text='Optionele bovenliggende organisatorische eenheid.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_organisatorische_eenheden', to='scim.organisatorischeeenheid'),
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='identificatie',
            field=models.CharField(default=1, help_text='Unieke interne identificatie van de organisatorische eenheid.', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='naam',
            field=models.CharField(default=1, help_text='Volledige naam van de organisatorische eenheid.', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='omschrijving',
            field=models.TextField(blank=True, help_text='Optionele omschrijving van de organisatorische eenheid.'),
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='soort_organisatie',
            field=models.CharField(default=1, help_text='Soort organisatorische eenheid.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='telefoonnummer',
            field=models.CharField(blank=True, help_text='Telefoonnummer van de organisatorische eenheid.', max_length=50),
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='verkorte_naam',
            field=models.CharField(blank=True, help_text='Afkorting of verkorte naam van de organisatorische eenheid.', max_length=50),
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='vestigingen',
            field=models.ManyToManyField(blank=True, help_text='Vestigingen waaraan de medewerker gekoppeld is.', related_name='organisatorische_eenheden', to='scim.vestiging'),
        ),
        migrations.AddField(
            model_name='team',
            name='naam',
            field=models.CharField(default=1, help_text='Naam van het team.', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='omschrijving',
            field=models.TextField(blank=True, help_text='Optionele omschrijving van het team.'),
        ),
        migrations.AddField(
            model_name='team',
            name='vestigingen',
            field=models.ManyToManyField(blank=True, help_text='Vestigingen waaraan de medewerker gekoppeld is.', related_name='teams', to='scim.vestiging'),
        ),
        migrations.AddField(
            model_name='vestiging',
            name='adres',
            field=models.CharField(blank=True, help_text='Fysiek adres van de vestiging (optioneel).', max_length=255),
        ),
        migrations.AddField(
            model_name='vestiging',
            name='correspondentieadres',
            field=models.CharField(blank=True, help_text='Adres voor correspondentie (optioneel).', max_length=255),
        ),
        migrations.AddField(
            model_name='vestiging',
            name='landcode',
            field=models.CharField(blank=True, help_text='ISO-landcode van de vestiging (bijv. NL, BE).', max_length=2),
        ),
        migrations.AddField(
            model_name='vestiging',
            name='naam',
            field=models.CharField(default=1, help_text='Volledige naam van de vestiging.', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vestiging',
            name='post_adres',
            field=models.CharField(blank=True, help_text='Post adres van de vestiging (optioneel).', max_length=255),
        ),
        migrations.AddField(
            model_name='vestiging',
            name='telefoonnummer',
            field=models.CharField(blank=True, help_text='Telefoonnummer van de vestiging (optioneel).', max_length=50),
        ),
        migrations.AddField(
            model_name='vestiging',
            name='verkorte_naam',
            field=models.CharField(blank=True, help_text='Afkorting of korte naam van de vestiging.', max_length=50),
        ),
        migrations.AddField(
            model_name='vestiging',
            name='vestigingsnummer',
            field=models.CharField(default=1, help_text='Unieke identificatiecode of nummer van de vestiging.', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medewerker',
            name='functies',
            field=models.ManyToManyField(blank=True, help_text='Functies van de medewerker.', related_name='medewerkers', to='scim.functie'),
        ),
        migrations.AlterField(
            model_name='medewerker',
            name='medewerker_id',
            field=models.CharField(help_text='ID van de medewerker.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='medewerker',
            name='organisatorische_eenheden',
            field=models.ManyToManyField(blank=True, help_text='Organisatorische eenheden waartoe de medewerker behoort.', related_name='medewerkers', to='scim.organisatorischeeenheid'),
        ),
        migrations.AlterField(
            model_name='medewerker',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='Teams van de medewerker.', related_name='medewerkers', to='scim.team'),
        ),
    ]
