# Generated by Django 5.2.3 on 2025-07-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0002_organisatorischeeenheid_alter_medewerker_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='team',
            name='user_set',
            field=models.ManyToManyField(blank=True, help_text='Medewerkers die lid zijn van dit team.', related_name='scim_groups', to='scim.medewerker', verbose_name='Medewerkers'),
        ),
    ]
