# Generated by Django 5.2.3 on 2025-07-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0002_organisatorischeeenheid_alter_medewerker_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='active',
            new_name='is_active',
        ),
    ]
