# Generated by Django 5.2.3 on 2025-09-02 14:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0002_organisatorischeeenheid_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactpersoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True)),
                ('name', models.CharField(help_text='Naam van het team.', max_length=100, unique=True, verbose_name='Naam')),
                ('function', models.TextField(blank=True, help_text='Optionele beschrijving van het team.', verbose_name='Beschrijving')),
                ('email_address', models.EmailField(blank=True, help_text='Contact e-mailadres van de organisatorische eenheid.', max_length=254, verbose_name='E-mailadres')),
                ('phone_number', models.CharField(blank=True, help_text='Contact telefoonnummer van de organisatorische eenheid.', max_length=50, verbose_name='Telefoonnummer')),
            ],
            options={
                'verbose_name': 'Contactpersoon',
                'verbose_name_plural': 'Contactpersoon',
            },
        ),
        migrations.RemoveField(
            model_name='organisatorischeeenheid',
            name='active',
        ),
        migrations.RemoveField(
            model_name='vestiging',
            name='active',
        ),
        migrations.RemoveField(
            model_name='vestiging',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='vestiging',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='vestiging',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='vestiging',
            name='name',
        ),
        migrations.AddField(
            model_name='medewerker',
            name='branch',
            field=models.ManyToManyField(blank=True, help_text='Vestigingen waaraan de medewerker gekoppeld is.', related_name='medewerkers', to='scim.vestiging', verbose_name='Vestigingen'),
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='email_address',
            field=models.EmailField(blank=True, help_text='E-mailadres van de organisatorische eenheid.', max_length=254, verbose_name='E-mailadres'),
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='end_date',
            field=models.DateField(blank=True, help_text='Optionele einddatum waarop de organisatorische eenheid wordt opgeheven of stopt te bestaan.', null=True, verbose_name='Einddatum'),
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='identifier',
            field=models.CharField(default=1, help_text='Unieke interne identificatie van de organisatorische eenheid.', max_length=50, unique=True, verbose_name='Identificatie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='organization_type',
            field=models.CharField(default=1, help_text='Type organisatie.', max_length=50, verbose_name='Type organisatie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Telefoonnummer van de organisatorische eenheid.', max_length=50, verbose_name='Telefoonnummer'),
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='short_name',
            field=models.CharField(blank=True, help_text='Afkorting of verkorte naam van de organisatorische eenheid.', max_length=50, verbose_name='Verkorte naam'),
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True),
        ),
        migrations.AddField(
            model_name='vestiging',
            name='branchname',
            field=models.CharField(default=1, help_text='Volledige naam van de vestiging.', max_length=100, unique=True, verbose_name='Naam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vestiging',
            name='branchnumber',
            field=models.CharField(default=1, help_text='Unieke identificatiecode of nummer van de vestiging.', max_length=50, unique=True, verbose_name='Vestigingsnummer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vestiging',
            name='correspondence_address',
            field=models.CharField(blank=True, help_text='Adres voor correspondentie (optioneel).', max_length=255, verbose_name='Correspondentieadres'),
        ),
        migrations.AddField(
            model_name='vestiging',
            name='country_code',
            field=models.CharField(blank=True, help_text='ISO-landcode van de vestiging (bijv. NL, BE).', max_length=2, verbose_name='Landcode'),
        ),
        migrations.AddField(
            model_name='vestiging',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Telefoonnummer van de vestiging (optioneel).', max_length=50, verbose_name='Telefoonnummer'),
        ),
        migrations.AddField(
            model_name='vestiging',
            name='postal_address',
            field=models.CharField(blank=True, help_text='Post adres van de vestiging (optioneel).', max_length=255, verbose_name='Post adres'),
        ),
        migrations.AddField(
            model_name='vestiging',
            name='short_name',
            field=models.CharField(blank=True, help_text='Afkorting of korte naam van de vestiging.', max_length=50, verbose_name='Korte naam'),
        ),
        migrations.AddField(
            model_name='vestiging',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unieke resource identifier (UUID4)', unique=True),
        ),
        migrations.AlterField(
            model_name='medewerker',
            name='email',
            field=models.EmailField(help_text='E-mailadres van de medewerker.', max_length=254, unique=True, verbose_name='E-mailadres'),
        ),
        migrations.AlterField(
            model_name='medewerker',
            name='gender_indicator',
            field=models.CharField(blank=True, choices=[('M', 'Man'), ('V', 'Vrouw'), ('X', 'Anders')], help_text='Geslachtsaanduiding (optioneel).', max_length=10, verbose_name='Geslachtsaanduiding'),
        ),
        migrations.AlterField(
            model_name='medewerker',
            name='job_title',
            field=models.CharField(blank=True, help_text='Functie van de medewerker (optioneel).', max_length=100, verbose_name='Functie'),
        ),
        migrations.AlterField(
            model_name='organisatorischeeenheid',
            name='name',
            field=models.CharField(help_text='Volledige naam van de organisatorische eenheid.', max_length=100, unique=True, verbose_name='Naam'),
        ),
        migrations.AlterField(
            model_name='vestiging',
            name='address',
            field=models.CharField(blank=True, help_text='Fysiek adres van de vestiging (optioneel).', max_length=255, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='medewerker',
            name='contactpersoon',
            field=models.ForeignKey(blank=True, help_text='Contactpersoon van de medewerker (optioneel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medewerkers', to='scim.contactpersoon', verbose_name='Contactpersoon'),
        ),
    ]
