# Generated by Django 5.2.3 on 2025-10-10 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0003_remove_medewerker_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpersoon',
            name='medewerker',
            field=models.ForeignKey(help_text='De medewerker die aan deze rol gekoppeld is.', on_delete=django.db.models.deletion.CASCADE, related_name='contactpersoon_roles', to='scim.medewerker'),
        ),
        migrations.AlterField(
            model_name='contactpersoon',
            name='organisatorische_eenheden',
            field=models.ManyToManyField(blank=True, help_text='Organisatorische eenheden waaraan de medewerker gekoppeld is.', related_name='contactpersonen', to='scim.organisatorischeeenheid'),
        ),
        migrations.AlterField(
            model_name='contactpersoon',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='Teams waaraan de medewerker gekoppeld is.', related_name='contactpersonen', to='scim.team'),
        ),
    ]
