# Generated by Django 5.2.3 on 2025-10-10 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0003_remove_medewerker_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpersoon',
            name='medewerker',
            field=models.ForeignKey(help_text='De medewerker die aan deze rol gekoppeld is.', on_delete=django.db.models.deletion.CASCADE, related_name='contactpersoon_roles', to='scim.medewerker'),
        ),
        migrations.AlterField(
            model_name='contactpersoon',
            name='organisatorische_eenheden',
            field=models.ManyToManyField(blank=True, help_text='Organisatorische eenheden waaraan de medewerker gekoppeld is.', related_name='contactpersonen', to='scim.organisatorischeeenheid'),
        ),
        migrations.AlterField(
            model_name='contactpersoon',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='Teams waaraan de medewerker gekoppeld is.', related_name='contactpersonen', to='scim.team'),
        ),
        migrations.AlterField(
            model_name='functie',
            name='begin_datum',
            field=models.DateField(help_text='De datum waarop de functie ingaat.'),
        ),
        migrations.AlterField(
            model_name='functie',
            name='eind_datum',
            field=models.DateField(blank=True, help_text='De datum waarop de functie eindigt.', null=True),
        ),
        migrations.AlterField(
            model_name='functie',
            name='functie_omschrijving',
            field=models.CharField(help_text='Korte omschrijving of titel van de functie.', max_length=255),
        ),
        migrations.AlterField(
            model_name='functie',
            name='functie_type',
            field=models.ForeignKey(help_text='Het type functie dat hieraan gekoppeld is.', on_delete=django.db.models.deletion.CASCADE, related_name='functies', to='scim.functietype'),
        ),
        migrations.AlterField(
            model_name='functietype',
            name='naam',
            field=models.CharField(help_text='De naam van het functietype (bijv. Manager, Medewerker).', max_length=50),
        ),
        migrations.AlterField(
            model_name='functietype',
            name='slug',
            field=models.SlugField(help_text='Unieke, URL-vriendelijke identificatie voor dit functietype.', max_length=100, unique=True),
        ),
    ]
