# Generated by Django 5.2.3 on 2025-07-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0003_rename_active_team_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Medewerkers die lid zijn van dit team.', related_name='teams', to='scim.medewerker', verbose_name='Medewerkers'),
        ),
    ]
