# Generated by Django 5.2.3 on 2025-10-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0004_alter_contactpersoon_medewerker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_number',
            field=models.CharField(blank=True, help_text='EmployeeNumber uit Entra / SCIM.', max_length=100),
        ),
    ]
