# Generated by Django 5.2.3 on 2025-10-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0002_attribuutmappingconfig_user_employee_number_and_more'),
        ('scim', '0004_alter_contactpersoon_medewerker_and_more'),
    ]

    operations = [
    ]
