# Generated by Django 5.2.3 on 2025-10-31 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0004_alter_contactpersoon_medewerker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medewerker',
            name='organisatorische_eenheden',
        ),
    ]
