# Generated by Django 5.2.3 on 2025-10-31 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0004_alter_contactpersoon_medewerker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medewerker',
            name='organisatorische_eenheden',
        ),
        migrations.AddField(
            model_name='organisatorischeeenheid',
            name='contactpersoon',
            field=models.ForeignKey(blank=True, help_text='De medewerker die contactpersoon is voor deze organisatorische eenheid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisatorische_eenheden_als_contactpersoon', to='scim.medewerker'),
        ),
        migrations.AddField(
            model_name='team',
            name='contactpersoon',
            field=models.ForeignKey(blank=True, help_text='De medewerker die contactpersoon is voor dit team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_als_contactpersoon', to='scim.medewerker'),
        ),
        migrations.DeleteModel(
            name='Contactpersoon',
        ),
    ]
