# Generated by Django 5.2.3 on 2025-11-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0005_merge_20251014_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribuutmappingconfig',
            name='actief',
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.CharField(blank=True, help_text='EmployeeNumber uit Entra / SCIM.', max_length=100),
        ),
    ]
