# Generated by Django 5.2.3 on 2025-11-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0005_remove_medewerker_organisatorische_eenheden_and_more'),
        ('scim', '0006_remove_attribuutmappingconfig_actief_and_more'),
    ]

    operations = [
    ]
