# Generated by Django 5.2.3 on 2025-11-10 14:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisatie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scim_id', models.CharField(blank=True, default=None, help_text='A unique identifier for a SCIM resource as defined by the service provider.', max_length=254, null=True, unique=True, verbose_name='SCIM ID')),
                ('scim_external_id', models.CharField(blank=True, db_index=True, default=None, help_text='A string that is an identifier for the resource as defined by the provisioning client.', max_length=254, null=True, verbose_name='SCIM External ID')),
                ('scim_display_name', models.CharField(blank=True, db_index=True, default=None, help_text='A human-readable name for the Group.', max_length=254, null=True, verbose_name='SCIM Display Name')),
                ('name', models.CharField(help_text='Naam van het team.', max_length=100, unique=True, verbose_name='Naam')),
                ('description', models.TextField(blank=True, help_text='Optionele beschrijving van het team.', verbose_name='Beschrijving')),
                ('active', models.BooleanField(default=True, help_text='Geeft aan of het team momenteel actief is.', verbose_name='Actief')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scim_id', models.CharField(blank=True, default=None, help_text='A unique identifier for a SCIM resource as defined by the service provider.', max_length=254, null=True, unique=True, verbose_name='SCIM ID')),
                ('scim_external_id', models.CharField(blank=True, db_index=True, default=None, help_text='A string that is an identifier for the resource as defined by the provisioning client.', max_length=254, null=True, verbose_name='SCIM External ID')),
                ('scim_username', models.CharField(blank=True, db_index=True, default=None, help_text="A service provider's unique identifier for the user", max_length=254, null=True, verbose_name='SCIM Username')),
                ('username', models.CharField(editable=False, help_text='User principal name van de medewerker.', max_length=100, verbose_name='User principal name')),
                ('employee_number', models.CharField(blank=True, help_text='EmployeeNumber uit Entra / SCIM.', max_length=100)),
                ('first_name', models.CharField(help_text='Voornaam van de medewerker.', max_length=100, verbose_name='Voornaam')),
                ('last_name', models.CharField(help_text='Achternaam van de medewerker.', max_length=100, verbose_name='Achternaam')),
                ('email', models.EmailField(help_text='E-mailadres van de medewerker.', max_length=254, unique=True, verbose_name='E-mailadres')),
                ('job_title', models.CharField(blank=True, help_text='Functie van de medewerker (optioneel).', max_length=100, verbose_name='Functie')),
                ('phone_number', models.CharField(blank=True, help_text='Telefoonnummer van de medewerker (optioneel).', max_length=30, verbose_name='Telefoonnummer')),
                ('is_active', models.BooleanField(default=True, help_text='Geeft aan of de medewerker momenteel actief is.', verbose_name='Actief')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Datum waarop de medewerker is toegevoegd.', verbose_name='Datum toegevoegd')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Datum waarop de medewerker voor het laatst is gewijzigd.', verbose_name='Laatst gewijzigd')),
                ('groups', models.ManyToManyField(blank=True, help_text='Groups van de user.', related_name='user_set', to='identiteit.group', verbose_name='Groups')),
                ('medewerker', models.ForeignKey(blank=True, help_text='De gekoppelde medewerker (optioneel, wordt automatisch gekoppeld).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organisatie.medewerker')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
