# Generated by Django 5.2.9 on 2026-03-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identiteit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
