# Generated by Django 5.2.13 on 2026-05-07 10:43

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGistExtension

class Migration(migrations.Migration):

    dependencies = [
        ('identiteit', '0002_remove_user_first_name_remove_user_job_title_and_more'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wijzigingsdatum', models.DateTimeField(auto_now=True)),
                ('periode', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identiteit.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identiteit.user')),
            ],
            options={
                'verbose_name': 'User Group',
                'verbose_name_plural': 'User Groups',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(
                to='identiteit.group',
                through='identiteit.UserGroup',
                blank=True,
                related_name='user_set',
                verbose_name='Groups',
                help_text='Groups van de user.',
            ),
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('user', '='), ('group', '='), ('periode', '&&')], name='no_overlapping_user_group_periode'),
        ),
    ]
